🔧 env : yarn classic → yarn berry로 마이그레이션
dnd-side-project/dnd-8th-1-frontend pull request #12
Opened 2023-01-27 11:18 UTC by jinyoung234

# 요약
zero-install, 유령 의존성 제거, node_modules의 여러 문제(모듈 탐색 과정에서의 비효율, 용량)로 인한 yarn berry로 마이그레이션 진행

# 사진 (구현 캡처)

# 작업 내용
- [x] yarn 버전 1.22.19에서 3.3.1로 변경
- [x] yarn berry를 IDE(vscode)와 통합
- [x] Husky, lint-staged 재 설치
- [x] package.json 내 prepare 스크립트 변경
- [x] pre-commit 스크립트 변경
- [x] @typescript-eslint/parser 설치
- [x] lintstagedrc.js 파일 추가
- [x] zero-install 적용

# 기타 (논의하고 싶은 부분)

# 타 직군 전달 사항

## 백엔드 전달 사항

## 디자이너 전달 사항

close #11

2023-01-28 01:59 UTC, dar-jeeling commented
메모 남겨두겠습니다. 

- [ ] vscode 터미널에 yarn set version berry 입력
- [ ] ZipFS - a zip file system extension 설치
- [ ] vscode 터미널에 yarn unplug 입력
- [ ] cmd + shift + p후 TypeScript 검색 후 적용[사진 1 참고]
- [ ] vscode 터미널에yarn dev, yarn build -> yarn start, yarn storybook 으로 local, production, storybook 환경에서 이상 확인

2023-01-28 02:09 UTC, dar-jeeling requested changes
확인했습니다.

1. **(P1)** 전체적으로 `.gitignore` 파일에 대해서 재확인이 필요한 듯 싶습니다. 몇몇 파일들에 대해서는 제대로 적용되지 않은 듯 하네요. 특히나 리뷰 달아놓은 부분은 반영해서 커밋해주시길 부탁드립니다. 요 부분 반영하시고 멘션해주시면 Approve 해드릴게요!
2. **(P5)** `.pnp` 파일들은 어떤 역할을 하는 파일인가요?

작업하시느라 수고하셨습니다.

2023-01-28 02:09 UTC, dar-jeeling commented on .gitignore
> +.yarn/*
P1; 전체적으로 `.yarn`에 대해서 `.gitignore` 가 적용되지 않은 것 같습니다. 확인 부탁드려요.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/74234333/215236533-ad3395ca-8b52-40c0-8f3e-fc4103e1cbaf.png">

2023-01-28 02:09 UTC, dar-jeeling commented on .gitignore
> -/.vscode
P1; 요 줄은 다시 추가해주시고, 관련 파일 삭제 후 재커밋 부탁드립니다. 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/74234333/215236515-a10e954a-f778-4bd2-adb0-cc819afcb211.png">

2023-01-28 02:11 UTC, dar-jeeling commented on .gitignore
> +.yarn/*
`/.yarn`, `/.vscode`의 형태로 등록해야할 것 같습니다.

2023-01-28 03:34 UTC, jinyoung234 commented on .gitignore
> +.yarn/*
.gitignore에 있는 zero-install 부분은 다 잘 반영된거 같은데 혹시 이유가 있을까요? .yarn/* 이거 때문이라면 저것도 반영 된건데 !부분이 .gitignore 적용안하는 부분이라 그렇습니다. 이건 yarn docs에서 이렇게 하라고 가이드 준거라 이렇게 적용했습니다. 

참고하시면 좋을거 같아 코멘트 남깁니다!

https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

2023-01-28 03:42 UTC, jinyoung234 commented on .gitignore
> -/.vscode
혹시 이것도 추가해야하는 이유가 따로 있으실까요..? 이거 추가한 이유가 yarn berry를 사용하면 ide 내에서 타입스크립트 인식이 안되서 sdk 추가를 필요로 합니다. `yarn dlx @yarnpkg/sdks vscode` 그래서 다음 명령어를 추가하게 되면 생성 되는 폴더가 .vscode 고 이건 제가 설정한게 아닌 sdk 내에서 설치한 파일이라 이걸 지울 경우 이 프로젝트를 클론 하거나 확인 하는 분들이 프로젝트에 타입스크립트 관련 수 많은 에러가 발견 될 우려가 있습니다. 

관련 링크 첨부해드립니다.

https://yarnpkg.com/getting-started/editor-sdks

2023-01-28 03:46 UTC, dar-jeeling commented on .gitignore
> +.yarn/*
아 적용하면 안되는 부분인지 몰랐습니다!

2023-01-28 03:47 UTC, dar-jeeling commented on .gitignore
> -/.vscode
제 vscode 설정이 탭 열리면 자동으로 저 폴더가 생기게 되어있거든요 (확장 프로그램 관련)
마찬가지로 설치한 확장 때문에 두신 것 같긴한데.. 그렇다면 vscode 가 실행될때 자동으로 생길 수도 있을것같긴합니다

2023-01-28 03:48 UTC, dar-jeeling commented on .gitignore
> -/.vscode
셋팅때문이라면 그냥 제가 앞으로 개발하면서 제 파일 생길때마다 수동으로 지우는걸로ㅋㅋㅋ..............

2023-01-28 04:48 UTC, jinyoung234 commented on .gitignore
> -/.vscode
ㅜㅜㅜㅜ.. 이건 생각 못했네여,,,, 혹시 추가적으로 수정해야할 사항들이 있을까여..?! 없다면 머지하고 pnp 파일 관련 슬랙에 남겨 놓겠습니다!

2023-01-29 12:34 UTC, dar-jeeling approved these changes

2023-01-29 12:37 UTC, merged